package main

var repos = []string{
	"flatiron-store-project-v-000",
	"advent_of_code",
	"biblioteca2_0",
	"blogsite",
	"c38-git-demo",
	"Dotfile",
	"dotfiles",
	"gdocs2md",
	"gh-action-dashboard",
	"git_app",
	"hellow",
	"helm",
	"JSproblems",
	"kubernetes-intro",
	"server",
	"starting-dotfile",
	"TDDIntro",
	"terraform",
	"tic_tac_toe_java",
	"tw101-exercises",
	"twu-biblioteca-edgar",
	"arthop-map-dev",
	"simple-map-template",
	"c40-git-demo",
	"c40-git-workshop",
	"frontend_intro_workshop",
	"Project_Organizer_BackEnd",
	"Project_Organizer_FrontEnd",
	"other-peoples-shelves",
	"mentor_program",
}
